name: CI-CD
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: clone-repo
        uses: actions/checkout@v3

      - name: install-node
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: install-dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      #   - name: run-tests
      #     run: npm test

    #   - name: deploy
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.SSH_HOST }}
    #       username: ${{ secrets.SSH_USERNAME }}
    #       key: ${{ secrets.SSH_KEY }}
    #       port: ${{ secrets.SSH_PORT }}
    #       script: |
    #         cd ~/workflows || mkdir workflows && cd ~/workflows
    #         git clone https://github.com/${{ github.repository }} . || git pull origin main
    #         npm install
    #         pm2 delete my_api_node
    #         pm2 start inde.js --name my_api_node
